jobs:
  build:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v3
    - continue-on-error: true
      name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        cache: maven
        distribution: temurin
        java-version: '11'
    - continue-on-error: true
      env:
        S_NUTZMAVEN_USER_ID: ${{secrets.S_NUTZMAVEN_USER_ID}}
        S_NUTZMAVEN_USER_PWD: ${{secrets.S_NUTZMAVEN_USER_PWD}}
      name: Build with Maven
      run: mvn -Dmaven.test.skip=true -B package source:jar deploy --file pom.xml
        -s mvn_settings.xml -DS_NUTZMAVEN_USER_ID=${{secrets.S_NUTZMAVEN_USER_ID}}
        -DS_NUTZMAVEN_USER_PWD=${{secrets.S_NUTZMAVEN_USER_PWD}}
name: Java CI with Maven
on:
  repository_dispatch:
    types: trigger-ga___maven.yml
